spring:
  application:
    name:  api-gateway-ms
server:
  port: 8321
zuul:
  routes:
    
    booking-ms:
      path: /booking/**
      service-id: booking-ms 
    flight-ms:
      path: /flight/**
      service-id: flight-ms
    schedule-ms:
      path: /schedule/**
      service-id: schedule-ms 
    airport-ms:
      path: /airport/**
      service-id: airport-ms 
    passenger-ms:
      path: /passenger/**
      service-id: passenger-
      
    login-ms-admin:
      path: /admin/**
      service-id: login-ms
      strip-prefix: false
    login-ms-users:
      path: /user/**
      service-id: login-ms
      #strip-prefix: false
    login-ms-public:
      path: /public/**
      service-id: login-ms
      #strip-prefix: false
      
      
      
      
      
      
    
